 function Comp = addComponents2Panel_Param(hPanel)

 h_Gap = 0.05;
 h_ratio = [1 2 1];
 nSubPanel = length(h_ratio);
 h_1 = 0.1;
 
 h_Calib = h_ratio(1)*h_1;
 h_Scale = h_ratio(2)*h_1;
 h_WaveBar = h_ratio(3)*h_1;
%  h_Gap = (1-h_Collect-h_WaveBar)/3;
 
 w_Button = 0.7;
 w_Gap = (1-w_Button)/2;
 
 FS = 11;
 BC_PB = [1 1 1]*0.25;
 BC_TB = [1 1 1]*0.5;

%% Calib
y0 = 1-h_Gap-h_Calib;
Comp.subPanel.Calib.hPanel = uipanel('parent', hPanel,...
                                'Unit', 'Normalized',...
                                'Position', [0, y0, 1, h_Calib], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'k',...
                                'ShadowColor',            'k');

Comp.subPanel.Calib.Pushbutton.Calib = uicontrol('parent', Comp.subPanel.Calib.hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Calibrate',...
                                'Unit', 'Normalized',...
                                'Position', [0.025 0.3 0.4 0.7], ...
                                'FontSize', 10, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_TB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Callback', @Callback_Pushbutton_Calib);

Comp.subPanel.Calib.Text.CalibValue = uicontrol('parent', Comp.subPanel.Calib.hPanel, ...
                                'Style', 'text',...
                                'Unit', 'Normalized',...
                                'Position', [0.45 0.1 0.55 0.8],...
                                'FontSize', 12, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'r',...
                                'String', 'kPa', ...
                                'Visible', 'on');

%% Scale
y0 = y0-h_Gap-h_Scale;
Comp.subPanel.Scale.hPanel = uipanel('parent', hPanel,...
                                'Unit', 'Normalized',...
                                'Position', [0, y0, 1, h_Scale], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');


%% WaveBar
y0 = y0-h_Gap-h_WaveBar;
Comp.subPanel.WaveBar.hPanel = uipanel('parent', hPanel,...
                                'Unit', 'Normalized',...
                                'Position', [0, y0, 1, h_WaveBar], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');
                            
Comp.subPanel.WaveBar.Togglebutton.WaveBar = uicontrol('parent', Comp.subPanel.WaveBar.hPanel, ...
                                'Style', 'togglebutton',...
                                'String', 'Bar',...
                                'Unit', 'Normalized',...
                                'Position', [w_Gap 0.1 w_Button 0.8], ...
                                'FontSize', 16, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_TB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Callback', @Callback_Togglebutton_WaveBar);



% Comp.Pushbutton.LoadSnake = uicontrol('parent', hPanel, ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'Load Snakes(Points)',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0.05 h 0.9 h_Load], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Pushbutton_SnakePanel_LoadSnake);
% 
% %% slice No
% h = h-h_Gap-h_SliceNo;
% Comp.hPanel.SliceNo = uipanel('parent', hPanel,...
%                                 'Unit', 'Normalized',...
%                                 'Position', [.05, h, .9, h_SliceNo], ...
%                                 'Title', '',...
%                                 'FontSize',                 10,...
%                                 'Units',                     'normalized', ...
%                                 'visible',                      'on', ...
%                                 'ForegroundColor',       'white',...
%                                 'BackgroundColor',       'black', ...
%                                 'HighlightColor',          'k',...
%                                 'ShadowColor',            'k');
% 
% nR = 3;
% columnRatio = [1];
% hSubPanel_SliceNo = addSubPanels(Comp.hPanel.SliceNo, nR, columnRatio);
%                             
% Comp.Pushbutton.StartSlice = uicontrol('parent', hSubPanel_SliceNo(1,1), ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'Start Slice',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Pushbutton_SnakePanel_StartSlice);
% 
% Comp.Pushbutton.EndSlice = uicontrol('parent', hSubPanel_SliceNo(2,1), ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'End Slice',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Pushbutton_SnakePanel_EndSlice);
% 
% Comp.Edit.StartSlice = uicontrol('parent', hSubPanel_SliceNo(1,2), ...
%                                 'Style', 'edit',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1],...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', 'k',...
%                                 'ForegroundColor', 'g',...
%                                 'String', '0', ...
%                                 'Visible', 'on');
% 
% Comp.Edit.EndSlice = uicontrol('parent', hSubPanel_SliceNo(2,2), ...
%                                 'Style', 'edit',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1],...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', 'k',...
%                                 'ForegroundColor', 'g',...
%                                 'String', '0', ...
%                                 'Visible', 'on');
% 
% Comp.Pushbutton.FreeHand = uicontrol('parent', hSubPanel_SliceNo(3,1), ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'Draw',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Pushbutton_SnakePanel_FreeHand);
%                             
% 
% %% redraw
% h = h-h_Gap*2-h_reDraw;
% Comp.hPanel.reDraw = uipanel('parent', hPanel,...
%                                 'Unit', 'Normalized',...
%                                 'Position', [.05, h, .9, h_reDraw], ...
%                                 'Title', '',...
%                                 'FontSize',                 10,...
%                                 'Units',                     'normalized', ...
%                                 'visible',                      'on', ...
%                                 'ForegroundColor',       'white',...
%                                 'BackgroundColor',       'black', ...
%                                 'HighlightColor',          'k',...
%                                 'ShadowColor',            'k');
% 
% nR = 1;
% columnRatio = [1];
% hSubPanel_reDraw = addSubPanels(Comp.hPanel.reDraw, nR, columnRatio);
% 
% Comp.Togglebutton.ReDraw = uicontrol('parent', hSubPanel_reDraw(1,1), ...
%                                 'Style', 'togglebutton',...
%                                 'String', 'reDraw',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_TB,...
%                                 'ForegroundColor', 'g',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Togglebutton_SnakePanel_ReDraw);
%                             
% Comp.Pushbutton.Delete = uicontrol('parent', hSubPanel_reDraw(1,2), ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'Delete',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Pushbutton_SnakePanel_DeleteSnake);
%  
% % save
% h = h-h_Gap-h_Save;
% Comp.Pushbutton.SaveSnake = uicontrol('parent', hPanel, ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'Save Snakes (Points)',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0.05 h 0.9 h_reDraw], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Pushbutton_SnakePanel_SaveSnake);
%                            
%                           