 function Comp = addComponents2Panel_Calib(hPanel)

BC_TB = [1 1 1]*0.5;

%% Calib
Comp.Pushbutton.Calib = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Calib',...
                                'Unit', 'Normalized',...
                                'Position', [0. 0.1 0.4 0.8], ...
                                'FontSize', 10, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_TB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Callback', @Callback_Pushbutton_Calib);

Comp.Text.CalibValue = uicontrol('parent', hPanel, ...
                                'Style', 'text',...
                                'Unit', 'Normalized',...
                                'Position', [0.4 0. 0.6 0.8],...
                                'FontSize', 10, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'r',...
                                'String', '0 kPa', ...
                                'Visible', 'on');