function Comp = addComponents2Panel_View(hPanel)

FC = [255 255 102]/255;
FC = [255 255 255]/255;

% axes
Comp.hAxis.Wave = axes('Parent',                   hPanel, ...
                            'color',        'none',...
                            'xcolor', FC,...
                            'ycolor', FC, ...
                            'gridcolor',   FC,...
                            'Units',                    'normalized', ...
                            'HandleVisibility',     'callback', ...
                            'Position',                 [0.1 0.1 0.85 0.85]);

Comp.hAxis.Wave.XLabel.String = 'Time (s)';                        
Comp.hAxis.Wave.YLabel.String = 'Pressure (kPa)';                        
% Comp.hAxis.Image.XAxisLocation='top';
hold(Comp.hAxis.Wave, 'on')

Comp.hPlotObj.Wave = line(Comp.hAxis.Wave, 'XData', [], 'YData', [],...
    'Marker', '.',  'MarkerSize', 24,...
    'Color', 'g', 'LineStyle', '-', 'LineWidth', 1);

Comp.hPlotObj.AvgLine = line(Comp.hAxis.Wave, 'XData', [], 'YData', [],...
    'Marker', 'none',  'MarkerSize', 24,...
    'Color', 'r', 'LineStyle', '-', 'LineWidth', 1);