function Comp = addComponents2Panel2_Menu(hPanel)

h_Gap = 0.05;
h_ratio = [1 1 1];
nSubPanel = length(h_ratio);
h_1 = (1-h_Gap*(nSubPanel+1))/sum(h_ratio);

h_Load = h_ratio(1)*h_1;
% h_Pic = h_ratio(2)*h_1;
% h_B = h_ratio(3)*h_1;
% h_BH = h_ratio(4)*h_1;
%  h_Gap = (1-h_Collect-h_WaveBar)/3;

w_Button = 0.9;
w_Gap = (1-w_Button)/2;

FS = 11;
BC_PB = [1 1 1]*0.25;
BC_TB = [1 1 1]*0.5;

y0 = 1;
% load data
y0 = y0-h_Gap-h_1;
Comp.Pushbutton.Load = uicontrol('parent', hPanel, ...
                            'Style', 'pushbutton',...
                            'String', 'Load Wave',...
                            'Unit', 'Normalized',...
                            'Position', [w_Gap, y0, w_Button, h_1], ...
                            'FontSize', 12, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', [1 1 1]*0.25,...
                            'ForegroundColor', 'c',...
                            'Value', 1, ...
                            'Visible', 'on', ...
                            'Enable', 'on', ...
                            'Tag', 'LoadData', ...
                            'Callback', @Callback_Pushbutton_LoadData);

y0 = y0-h_Gap-h_1;
Comp.Pushbutton.Thresh = uicontrol('parent', hPanel, ...
                            'Style', 'pushbutton',...
                            'String', 'Threshold',...
                            'Unit', 'Normalized',...
                            'Position', [w_Gap, y0, w_Button, h_1], ...
                            'FontSize', 12, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', [1 1 1]*0.25,...
                            'ForegroundColor', 'c',...
                            'Value', 1, ...
                            'Visible', 'on', ...
                            'Enable', 'off', ...
                            'Tag', 'LoadData', ...
                            'Callback', @Callback_Pushbutton_ThreshSetting);

y0 = y0-h_Gap-h_1;
Comp.Pushbutton.Save = uicontrol('parent', hPanel, ...
                            'Style', 'pushbutton',...
                            'String', 'Save Data',...
                            'Unit', 'Normalized',...
                            'Position', [w_Gap, y0, w_Button, h_1], ...
                            'FontSize', 12, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', [1 1 1]*0.25,...
                            'ForegroundColor', 'c',...
                            'Value', 1, ...
                            'Visible', 'on', ...
                            'Enable', 'off', ...
                            'Tag', 'LoadData', ...
                            'Callback', @Callback_Pushbutton_SaveAnalysis);