 function Comp = addComponents2Panel_TextBox(hPanel)

  Comp.Text.Text = uicontrol('parent', hPanel, ...
                                'Style', 'text',...
                                'String', 'Hello!',...
                                'Unit', 'Normalized',...
                                'Position', [0. 0 1 1], ...
                                'FontSize', 36, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'w',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'HorizontalAlignment', 'left');