 function Comp = addComponents2Panel_BHC(hPanel)

Comp.Edit.Counter = uicontrol('parent', hPanel, ...
                                'Style', 'edit',...
                                'Unit', 'Normalized',...
                                'Position', [0 0 1 1],...
                                'FontSize', 64, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.1,...
                                'ForegroundColor', 'g',...
                                'String', '20', ...
                                'Visible', 'on');