function Comp = addComponents2Panel_View(hPanel)

FC = [255 255 102]/255;
FC = [255 255 255]/255;

% axes
Comp.hAxis.Wave = axes('Parent',                   hPanel, ...
                            'color',        'none',...
                            'xcolor', FC,...
                            'ycolor', FC, ...
                            'gridcolor',   FC,...
                            'Units',                    'normalized', ...
                            'HandleVisibility',     'callback', ...
                            'Position',                 [0.075 0.075 0.9 0.9]);

Comp.hAxis.Wave.XLabel.String = 'Time (s)';                        
% Comp.hAxis.Image.XAxisLocation='top';
hold(Comp.hAxis.Wave, 'on')

Comp.hPlotObj.Wave = line(Comp.hAxis.Wave, 'XData', [], 'YData', [],...
    'Marker', '.',  'MarkerSize', 12,...
    'Color', 'g', 'LineStyle', '-');
