function Comp = addComponents2Panel_BHC(hPanel)

global BHC
 
Comp.Edit.Counter = uicontrol('parent', hPanel, ...
                                'Style', 'edit',...
                                'Unit', 'Normalized',...
                                'Position', [0 0 1 1],...
                                'FontSize', 64, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.1,...
                                'ForegroundColor', 'g',...
                                'String', num2str(BHC), ...
                                'Visible', 'on', ...
                                'Callback', @Callback_Edit_BHC);