function Comp = addComponents2Panel2_TableB(hPanel)

% global wgBAll wgColor hwgB
global BoxColor

nB = 6;
h_gap = 0.05;
hB = (1-h_gap*(1+nB))/nB;

for n = 1:nB
    yy(n) = h_gap*(nB-n+1)+hB*(nB-n);
end
for n = 1:nB
    y = yy(n);
    Comp.Radiobutton.Box(n) = uicontrol('parent', hPanel, ...
                            'Style', 'radiobutton',...
                            'String', [' ', num2str(n)],...
                            'Unit', 'Normalized',...
                            'Position', [0.1 y 0.3 hB], ...
                            'FontSize', 12, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', BoxColor(n,:),...
                            'ForegroundColor', 'w',...
                            'Value', 1, ...
                            'Visible', 'off', ...
                            'Enable', 'on', ...
                            'Tag', num2str(n), ...
                            'Callback', @Callback_Radiobutton_TableB_Box_);
end

for n = nB+1:nB+nB
    y = yy(n-nB);
    Comp.Radiobutton.Box(n) = uicontrol('parent', hPanel, ...
                            'Style', 'radiobutton',...
                            'String', [' ', num2str(n)],...
                            'Unit', 'Normalized',...
                            'Position', [0.6 y 0.3 hB], ...
                            'FontSize', 12, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', [1 1 1]*0.1,...
                            'ForegroundColor', BoxColor(n,:),...
                            'Value', 1, ...
                            'Visible', 'off', ...
                            'Enable', 'on', ...
                            'Tag', num2str(n), ...
                            'Callback', @Callback_Radiobutton_TableB_Box_);
end
