 function Comp = addComponents2Panel_ParamButton(hPanel)

 Comp.Pushbutton.About = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Setting',...
                                'Unit', 'Normalized',...
                                'Position', [0.25 0.2 0.5 0.6], ...
                                'FontSize', 11, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Callback', @Callback_Pushbutton_ParamButton);