 function Comp = addComponents2Panel_Collect(hPanel)

 h_Collect = 0.8;
 h_Gap = (1-h_Collect)/2;

 w_Button = 0.6;
 w_Gap = (1-w_Button)/2;
 
nG = 3;

FS = 24;
BC_PB = [1 1 1]*0.25;
BC_TB = [1 1 1]*0.5;

% Collect
y0 = 1-h_Gap-h_Collect;
Comp.Togglebutton.Collect = uicontrol('parent', hPanel, ...
                                'Style', 'togglebutton',...
                                'String', 'Go',...
                                'Unit', 'Normalized',...
                                'Position', [w_Gap y0 w_Button h_Collect], ...
                                'FontSize', 24, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_TB,...
                                'ForegroundColor', 'g',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Callback', @Callback_Togglebutton_Collect);