 function Comp = addComponents2Panel_TextButton(hPanel)

 Comp.Pushbutton.Text = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Text',...
                                'Unit', 'Normalized',...
                                'Position', [0. 0.2 1 0.6], ...
                                'FontSize', 11, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Callback', @Callback_Pushbutton_TextButton);