function Comp = addComponents2Panel2_SyncYLim(hPanel)

Comp.Pushbutton.SyncYLim = uicontrol('parent', hPanel, ...
                            'Style', 'pushbutton',...
                            'String', 'Sync',...
                            'Unit', 'Normalized',...
                            'Position', [0. 0 1 1], ...
                            'FontSize', 11, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', 'k',...
                            'ForegroundColor', 'c',...
                            'Visible', 'on', ...
                            'Enable', 'on', ...
                            'Callback', @Callback_Pushbutton_SyncYLim_);