function Comp = addComponents2Panel2_DeleteB(hPanel)

% global wgBAll wgColor hwgB
global BoxColor

nB = 2;
h_gap = 0.05;
hB = (1-h_gap*(1+nB))/nB;

for n = 1:nB
    yy(n) = h_gap*(nB-n+1)+hB*(nB-n);
end

w_gap = 0.05;
wRatio = [2 1];
nB = numel(wRatio);
w1 = (1-w_gap*(nB+1))/sum(wRatio);
for n = 1:nB
    w(n) = w1*wRatio(n);
end
% x(1) = wRatio(1);
for n = 1:nB
    x(n) = w_gap*n+sum(w(1:n-1));
end

% for n = 1:10
%     cS{n} = num2str(n-1);
% end
% 
Comp.PopUpMenu.BoxList = uicontrol('parent', hPanel,...
                                    'Style',  'popupmenu',...
                                    'Units',                          'normalized', ...
                                    'Position',                      [x(1) 0.1 w(1) 0.8],...
                                    'ForegroundColor',         [1 1 1],...
                                     'BackgroundColor',         [0 0 0],...
                                    'FontSize',                     12, ...
                                    'FontWeight', 'bold', ...
                                    'String', '  Box');
                       
% hPopUpMenu.cutSlice.Value = 5;           

Comp.Pushbutton.Delete = uicontrol('parent', hPanel, ...
                            'Style', 'Pushbutton',...
                            'String', 'X',...
                            'Unit', 'Normalized',...
                            'Position',                      [x(2) .05 w(2) .9],...
                            'FontSize', 12, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', 'k',...
                            'ForegroundColor', 'r',...
                            'Visible', 'on', ...
                            'Enable', 'on', ...
                            'Tag', num2str(n), ...
                            'Callback', @Callback_Pushbutton_DeleteB);