function Comp = addComponents2Panel2_ParamB(hPanel)

nB = 3;
h_gap = 0.01;
hB = (1-h_gap*(1+nB))/nB;

paramName{1} = 'GAV';
paramName{2} = 'PV';
paramName{3} = 'LAV';

for n = 1:nB
    yy(n) = h_gap*(nB-n+1)+hB*(nB-n);
end
for n = 1:nB
    y = yy(n);
    Comp.Text.ParamName(n) = uicontrol('parent', hPanel, ...
                            'Style', 'text',...
                            'String', paramName{n},...
                            'Unit', 'Normalized',...
                            'Position', [0. y 0.4 hB], ...
                            'FontSize', 16, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', [1 1 1]*0,...
                            'ForegroundColor', 'w',...
                            'Visible', 'on', ...
                            'Enable', 'on');
end

for n = 1:nB
    y = yy(n);
    Comp.Text.ParamValue(n) = uicontrol('parent', hPanel, ...
                            'Style', 'text',...
                            'String', paramName{n},...
                            'Unit', 'Normalized',...
                            'Position', [0.4 y 0.6 hB], ...
                            'FontSize', 16, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', 'k',...
                            'ForegroundColor', 'g',...
                            'Visible', 'on', ...
                            'Enable', 'on');
end