 function Comp = addComponents2Panel_PtInfo(hPanel)

h_Gap = 0.1;
nH = 3;
h_C = (1-h_Gap*(nH+1))/nH;
 
w_Gap = 0.025;
nW = 2;
w_C1 = 0.3;
w_C2 = 1-w_Gap*(nW+1)-w_C1;
 
FS = 10;
BC_PB = [1 1 1]*0.25;
BC_TB = [1 1 1]*0.5;

%% MRN
y0 = 1-h_Gap-h_C;
Comp.Pushbutton.SP = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'Unit', 'Normalized',...
                                'Position', [0.1 y0 0.8 h_C],...
                                'FontSize', 11, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'c',...
                                'String', 'Search Patient', ...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_PatientSearch);

y0 = y0-h_Gap-h_C;
Comp.Text.MRN = uicontrol('parent', hPanel, ...
                                'Style', 'Text',...
                                'Unit', 'Normalized',...
                                'Position', [w_Gap y0 w_C1 h_C],...
                                'FontSize', 9, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'w',...
                                'String', 'MRN', ...
                                'Visible', 'on');
                            
Comp.Edit.MRN = uicontrol('parent', hPanel, ...
                                'Style', 'edit',...
                                'Unit', 'Normalized',...
                                'Position', [w_Gap*2+w_C1 y0 w_C2 h_C],...
                                'FontSize', 11, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'g',...
                                'String', 'MRN', ...
                                'Visible', 'on');

y0 = y0-h_Gap-h_C;
Comp.Text.Fraction = uicontrol('parent', hPanel, ...
                                'Style', 'Text',...
                                'Unit', 'Normalized',...
                                'Position', [w_Gap y0 w_C1 h_C],...
                                'FontSize', 9, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'w',...
                                'String', 'Fraction', ...
                                'Visible', 'on');
                            
Comp.Edit.Fraction = uicontrol('parent', hPanel, ...
                                'Style', 'edit',...
                                'Unit', 'Normalized',...
                                'Position', [w_Gap*2+w_C1 y0 w_C2 h_C],...
                                'FontSize', 11, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'g',...
                                'String', 'Fx', ...
                                'Visible', 'on');
