function Comp = addComponents2Panel2_TableBH(hPanel)

% global wgBAll wgColor hwgB
global BoxColor

nR = 8;
h_gap = 0.05;
hB = (1-h_gap*(1+nR))/nR;
for n = 1:nR
    yy(n) = h_gap*(nR-n+1)+hB*(nR-n);
end

nC = 3;
w_gap = 0.05;
wB = (1-w_gap*(1+nC))/nC;
for n = 1:nC
    xx(n) = w_gap*n + wB*(n-1);
end

n = 0;
for iC = 1:nC
    x = xx(iC);
    for iR = 1:nR
        y = yy(iR);
        n = n+1;
        Comp.Radiobutton.Box(n) = uicontrol('parent', hPanel, ...
                                'Style', 'radiobutton',...
                                'String', [' ', char(n+'A'-1)],...
                                'Unit', 'Normalized',...
                                'Position', [x y wB hB], ...
                                'FontSize', 12, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BoxColor(n,:),...
                                'ForegroundColor', 'w',...
                                'Value', 1, ...
                                'Visible', 'off', ...
                                'Enable', 'on', ...
                                'Tag', num2str(n), ...
                                'Callback', @Callback_Radiobutton_TableBH_Box_);
    end
end

% for n = nR+1:nR+nR
%     y = yy(n-nR);
%     Comp.Radiobutton.Box(n) = uicontrol('parent', hPanel, ...
%                             'Style', 'radiobutton',...
%                             'String', [' ', char(n+'A'-1)],...
%                             'Unit', 'Normalized',...
%                             'Position', [0.6 y 0.3 hB], ...
%                             'FontSize', 12, ...
%                             'FontWeight', 'bold', ...
%                             'BackgroundColor', BoxColor(n,:),...
%                             'ForegroundColor', 'w',...
%                             'Value', 1, ...
%                             'Visible', 'on', ...
%                             'Enable', 'on', ...
%                             'Tag', num2str(n), ...
%                             'Callback', @Callback_Radiobutton_TableBH_Box_);
% end
