 function Comp = addComponents2Panel_ParamButton(hPanel)

 Comp.Pushbutton.About = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Parameters',...
                                'Unit', 'Normalized',...
                                'Position', [0.1 0.1 0.8 0.8], ...
                                'FontSize', 11, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Callback', @Callback_Pushbutton_ParamButton);