function Comp = addComponents2Panel2_TableB(hPanel)

global wgBAll wgColor hwgB

nB = 6;
h_gap = 0.05;
hB = (1-h_gap*(1+nB))/nB;

for n = 1:nB
    y(n) = h_gap*(nB-n+1)+hB*(nB-n);
    Comp.Radiobutton.Box(n) = uicontrol('parent', hPanel, ...
                            'Style', 'radiobutton',...
                            'String', num2str(n),...
                            'Unit', 'Normalized',...
                            'Position', [0.4 y(n) 0.2 hB], ...
                            'FontSize', 12, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', [1 1 1]*0.1,...
                            'ForegroundColor', wgColor(n,:),...
                            'Value', 1, ...
                            'Visible', 'off', ...
                            'Enable', 'on', ...
                            'Tag', ['Box', num2str(n)], ...
                            'Callback', @Callback_Radiobutton_TableB_Box_);
end
