 function Comp = addComponents2Panel_Menu(hPanel)

 h_Gap = 0.025;
 h_Load = 0.15;
 h_SliceNo = 0.4;
 h_reDraw = 0.15;
 h_Save = 0.15;
 
 w_Button = 0.9;
 x_Button = (1-w_Button)/2;
 
nG = 3;

FS = 11;
BC_PB = [1 1 1]*0.25;
BC_TB = [1 1 1]*0.5;

gapLeft = 0.025;
gapTop = 0.1;
h_Button = 1-gapTop*2;
w_Button = 0.075;

% Collect
Comp.Togglebutton.Collect = uicontrol('parent', hPanel, ...
                                'Style', 'togglebutton',...
                                'String', 'Collect',...
                                'Unit', 'Normalized',...
                                'Position', [gapLeft gapTop w_Button h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_TB,...
                                'ForegroundColor', 'g',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Callback', @Callback_Togglebutton_Collect);



% Comp.Pushbutton.LoadSnake = uicontrol('parent', hPanel, ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'Load Snakes(Points)',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0.05 h 0.9 h_Load], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Pushbutton_SnakePanel_LoadSnake);
% 
% %% slice No
% h = h-h_Gap-h_SliceNo;
% Comp.hPanel.SliceNo = uipanel('parent', hPanel,...
%                                 'Unit', 'Normalized',...
%                                 'Position', [.05, h, .9, h_SliceNo], ...
%                                 'Title', '',...
%                                 'FontSize',                 10,...
%                                 'Units',                     'normalized', ...
%                                 'visible',                      'on', ...
%                                 'ForegroundColor',       'white',...
%                                 'BackgroundColor',       'black', ...
%                                 'HighlightColor',          'k',...
%                                 'ShadowColor',            'k');
% 
% nR = 3;
% columnRatio = [1];
% hSubPanel_SliceNo = addSubPanels(Comp.hPanel.SliceNo, nR, columnRatio);
%                             
% Comp.Pushbutton.StartSlice = uicontrol('parent', hSubPanel_SliceNo(1,1), ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'Start Slice',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Pushbutton_SnakePanel_StartSlice);
% 
% Comp.Pushbutton.EndSlice = uicontrol('parent', hSubPanel_SliceNo(2,1), ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'End Slice',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Pushbutton_SnakePanel_EndSlice);
% 
% Comp.Edit.StartSlice = uicontrol('parent', hSubPanel_SliceNo(1,2), ...
%                                 'Style', 'edit',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1],...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', 'k',...
%                                 'ForegroundColor', 'g',...
%                                 'String', '0', ...
%                                 'Visible', 'on');
% 
% Comp.Edit.EndSlice = uicontrol('parent', hSubPanel_SliceNo(2,2), ...
%                                 'Style', 'edit',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1],...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', 'k',...
%                                 'ForegroundColor', 'g',...
%                                 'String', '0', ...
%                                 'Visible', 'on');
% 
% Comp.Pushbutton.FreeHand = uicontrol('parent', hSubPanel_SliceNo(3,1), ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'Draw',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Pushbutton_SnakePanel_FreeHand);
%                             
% 
% %% redraw
% h = h-h_Gap*2-h_reDraw;
% Comp.hPanel.reDraw = uipanel('parent', hPanel,...
%                                 'Unit', 'Normalized',...
%                                 'Position', [.05, h, .9, h_reDraw], ...
%                                 'Title', '',...
%                                 'FontSize',                 10,...
%                                 'Units',                     'normalized', ...
%                                 'visible',                      'on', ...
%                                 'ForegroundColor',       'white',...
%                                 'BackgroundColor',       'black', ...
%                                 'HighlightColor',          'k',...
%                                 'ShadowColor',            'k');
% 
% nR = 1;
% columnRatio = [1];
% hSubPanel_reDraw = addSubPanels(Comp.hPanel.reDraw, nR, columnRatio);
% 
% Comp.Togglebutton.ReDraw = uicontrol('parent', hSubPanel_reDraw(1,1), ...
%                                 'Style', 'togglebutton',...
%                                 'String', 'reDraw',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_TB,...
%                                 'ForegroundColor', 'g',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Togglebutton_SnakePanel_ReDraw);
%                             
% Comp.Pushbutton.Delete = uicontrol('parent', hSubPanel_reDraw(1,2), ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'Delete',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0 0 1 1], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Pushbutton_SnakePanel_DeleteSnake);
%  
% % save
% h = h-h_Gap-h_Save;
% Comp.Pushbutton.SaveSnake = uicontrol('parent', hPanel, ...
%                                 'Style', 'pushbutton',...
%                                 'String', 'Save Snakes (Points)',...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0.05 h 0.9 h_reDraw], ...
%                                 'FontSize', FS, ...
%                                 'FontWeight', 'bold', ...
%                                 'BackgroundColor', BC_PB,...
%                                 'ForegroundColor', 'c',...
%                                 'Visible', 'on', ...
%                                 'Enable', 'off', ...
%                                 'Callback', @Callback_Pushbutton_SnakePanel_SaveSnake);
%                            
%                           