 function Comp = addComponents2Panel_TextWin(hPanel)

  Comp.Edit.Text = uicontrol('parent', hPanel, ...
                                'Style', 'edit',...
                                'String', '',...
                                'Unit', 'Normalized',...
                                'Position', [0. 0.3 1 0.7], ...
                                'FontSize', 16, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'w',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'HorizontalAlignment', 'left', ...
                                'Max', 2);
 
 
 Comp.Pushbutton.Send = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Send',...
                                'Unit', 'Normalized',...
                                'Position', [0.2 0.1 0.6 0.1], ...
                                'FontSize', 11, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.25,...
                                'ForegroundColor', 'g',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Callback', @Callback_Pushbutton_TextSend);