function Panel = addPanel2(hFig)

w1 = 0.5;
w2 = 1-w1;
h1 = 0.3;
h2 = 1-h1;

Panel.Bar.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 0, 1, 1-0.075], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'k',...
                                'ShadowColor',            'k');