function Panel = addPanel(hFig)

h_LoadImage = 0.2;
h_Selection = 0.05;
h_Snake = 0.4;
h_Point = 0.3;
h_About = 1-h_LoadImage-h_Snake-h_Point-h_Selection;
h_ContrastBar = 0.05;
h_View = 1-h_ContrastBar;

h_Menu = 0.075;
h_View = 1-h_Menu;

Panel.View.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, 0, 1, h_View], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');%% Menu

Panel.Menu.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, h_View, 1, h_Menu], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

