function Panel = addPanel(hFig)

w_Menu = 0.15;
w_View = 1-w_Menu;

h_PtInfo = 0.15;
h_Go = 0.1;
h_WaveBar = 0.1;
h_ParamButton = 0.075;
h_Calib = 0.05;
h_Param = 1-h_PtInfo-h_Go-h_WaveBar-h_ParamButton-h_Calib;

%% Patient Info
y0 = 1-h_PtInfo;
Panel.PtInfo.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, y0, w_Menu, h_PtInfo], ...
                                'Title', 'Patient Info',...
                                'FontSize',                 11,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'b',...
                                'ShadowColor',            'k');
                            
                            
%% Go
y0 = y0-h_Go;
Panel.Collect.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, y0, w_Menu, h_Go], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'k',...
                                'ShadowColor',            'k');

%% WaveBar
y0 = y0-h_WaveBar;
Panel.WaveBar.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, y0, w_Menu/2, h_WaveBar], ...
                                'Title', 'Wave/Bar',...
                                'FontSize',                 11,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'b',...
                                'ShadowColor',            'k');

%% BH
Panel.BH.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [ w_Menu/2, y0, w_Menu/2, h_WaveBar], ...
                                'Title', 'Breath Hold',...
                                'FontSize',                 11,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'b',...
                                'ShadowColor',            'k');

%% BH counter
Panel.BHC.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0.925, 0.9, 0.074, 0.095], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'k',...
                                'ShadowColor',            'k');
                            
%% param buttion
y0 = y0-h_ParamButton;
Panel.ParamButton.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, y0, w_Menu/2, h_ParamButton], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'k',...
                                'ShadowColor',            'k');
                            
%% Calib
y0 = y0-h_Calib;
Panel.Calib.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, y0, w_Menu, h_Calib], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'b',...
                                'ShadowColor',            'k');
                            
%% param
y0 = y0-h_Param;
Panel.Param.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, y0, w_Menu, h_Param], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'b',...
                                'ShadowColor',            'k');
                            
%% wave & bar
Panel.Wave.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [w_Menu, 0, w_View, 1], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');%% Menu

Panel.Bar.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [w_Menu, 0, w_View, 1], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'off', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');%% Menu

%% top
uistack(Panel.BHC.hPanel, 'top');
