function Callback_Pushbutton_About(src, evnt)

figHandles = get(0, 'Children');

if isempty(find(contains({figHandles.Tag}, 'About')))

hF = figure('MenuBar',            'none', ...
                    'Toolbar',              'none', ...
                    'HandleVisibility',  'callback', ...
                    'Name',                '', ...
                    'NumberTitle',      'off', ...
                    'Units',                 'normalized',...
                    'Position',             [0.35 0.4 0.3 0.1],...
                    'Color',                 'black', ...
                    'Visible',               'on', ...
                    'Tag', 'About');
% hA = axes('parent', hF);


hText = uicontrol('Parent', hF, ...
                                'Style', 'text', ...
                                'Units',                     'normalized', ...
                                'Position', [0.1 0.7 0.8, 0.2], ...
                                'FontSize', 12, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0,...
                                'ForegroundColor', 'c',...
                                'String', 'VIZ v1.0 - 2021.1.31');

hText = uicontrol('Parent', hF, ...
                                'Style', 'text', ...
                                'Units',                     'normalized', ...
                                'Position', [0.1 0.3 0.8, 0.2], ...
                                'FontSize', 10, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0,...
                                'ForegroundColor', 'c',...
                                'String', 'Zhen Ji & Taeho Kim ');
                            
hText = uicontrol('Parent', hF, ...
                                'Style', 'text', ...
                                'Units',                     'normalized', ...
                                'Position', [0. 0.1 1, 0.2], ...
                                'FontSize', 10, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0,...
                                'ForegroundColor', 'c',...
                                'String', 'Department of Radiation Oncology, Washington University in St. Louis');          
end